apiVersion: v1
kind: Service
metadata:
    name: faucet-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: faucet-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: faucet-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: faucet-nginx
    template:
        metadata:
            labels:
                app: faucet-nginx
        spec:
            containers:
                -   name: faucet-nginx
                    image: docker.pkg.github.com/extraton/faucet/faucet-worker:0.3.1
                    ports: [{containerPort: 80}]
                    command: ['/bin/bash']
                    args: ['-c', "php-fpm --nodaemonize & nginx -g 'daemon off;'"]
                    env:
                        - name: APP_ENV
                          value: "prod"
                        - name: APP_SECRET
                          value: ""
                        - name: APP_VERSION
                          value: "0.3.1"
                        - name: SITE_NAME
                          value: "Faucet.extraTON"
                        - name: DOMAIN
                          value: "faucet.extraton.io"
                        - name: RECAPTCHA_SITE_KEY
                          value: "6LcxKI4aAAAAACit3yybK5N-VE53t4ag5j7Kg288"
                        - name: RECAPTCHA_SECRET_KEY
                          value: ""
                        - name: WALLET_ADDRESS
                          value: "0:f17d533a33604cbfd106fd367830ee705d4afeee95682bc836e4847a89e807d5"
                        - name: WALLET_PUBLIC
                          value: "e88d332d51835be6599ecfca6d9b61e427764e47203615ab32c1aba0e00b09fa"
                        - name: WALLET_SECRET
                          value: ""
                        - name: WALLET_COLD_ADDRESS
                          value: "0:52cf349917fdebcbc104db38772592b2fb2626c4d9eb178010628ead737d1b15"
                        - name: DATABASE_URL
                          value: "mysql://faucet:pass@127.0.0.1:3306/faucet?serverVersion=mariadb-10.5.6"
            imagePullSecrets:
                -   name: github-registry
