apiVersion: v1
kind: Service
metadata:
    name: faucet-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: faucet-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: faucet-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: faucet-nginx
    template:
        metadata:
            labels:
                app: faucet-nginx
        spec:
            containers:
                -   name: faucet-nginx
                    image: docker.pkg.github.com/extraton/faucet/faucet-worker:0.1.1
                    ports: [{containerPort: 80}]
                    command: ['/bin/bash']
                    args: ['-c', "php-fpm --nodaemonize & nginx -g 'daemon off;'"]
            imagePullSecrets:
                -   name: github-registry
