request:
  path: /request
  controller: App\Controller\IndexController::request
  methods: [POST]

index:
  path: /{route}
  controller: App\Controller\IndexController::index
  methods: [GET]
  requirements: {route: '^.+'}
  defaults: {route: null}
